name: main

on:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'
          check-latest: true
          cache-dependency-path: "**/*.sum"
      - run: go version
      - uses: bufbuild/buf-setup-action@v1.42.0
        with:
          version: 'latest'
      - name: Buf Version
        run: buf --version
      - name: Install connectrpc
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
          go install connectrpc.com/connect/cmd/protoc-gen-connect-go@latest
      - name: Protogen
        run: buf generate --template buf.gen.yaml --path protos/chief-of-state-protos/chief_of_state/v1
      - name: Release
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
