name: pr

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'
          check-latest: true
          cache-dependency-path: "**/*.sum"
      - run: go version
      - name: Vendoring and Tidy
        run: go mod tidy && go mod vendor
      - uses: bufbuild/buf-setup-action@v1.42.0
        with:
          version: 'latest'
      - name: Buf Version
        run: buf --version
      - name: Install Protoc
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - name: Protogen
        run: buf generate --template buf.gen.yaml --path protos/chief-of-state-protos/chief_of_state/v1
